create type public.status as enum (
  'Like New',
  'Lightly Used',
  'Heavily Used',
  'Damaged',
  'In Repair'
);

create table public.items (
  id bigint generated always as identity not null,
  thing_id bigint not null,
  brand text null,
  estimated_value numeric(10, 2) null,
  hidden boolean null default false,
  location_id bigint null,
  notes text null,
  number bigint generated by default as identity not null,
  status public.status null,
  constraint items_pkey primary key (id),
  constraint items_number_key unique (number),
  constraint items_location_id_fkey foreign KEY (location_id) references item_locations (id) on delete set null,
  constraint items_thing_id_fkey foreign KEY (thing_id) references things (id) on delete CASCADE
) TABLESPACE pg_default;