create table public.loans_items (
  id bigint generated by default as identity not null,
  loan_id bigint null,
  item_id bigint null,
  returned boolean not null default false,
  thing_id bigint null,
  constraint loans_items_pkey primary key (id),
  constraint loans_items_item_id_fkey foreign KEY (item_id) references items (id) on update CASCADE on delete CASCADE,
  constraint loans_items_loan_id_fkey foreign KEY (loan_id) references loans (id) on update CASCADE on delete CASCADE,
  constraint loans_items_thing_id_fkey foreign KEY (thing_id) references things (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;