create table public.members_payments (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  member_id bigint null,
  constraint members_payments_pkey primary key (id),
  constraint members_payments_member_id_fkey foreign KEY (member_id) references members (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;