create table public.things_associations (
  id bigint generated by default as identity not null,
  thing_id bigint not null,
  associated_thing_id bigint not null,
  constraint things_associations_pkey primary key (id),
  constraint things_associations_associated_thing_id_fkey foreign KEY (associated_thing_id) references things (id) on update CASCADE on delete CASCADE,
  constraint things_associations_thing_id_fkey foreign KEY (thing_id) references things (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;