create type "public"."status" as enum ('Like New', 'Lightly Used', 'Heavily Used', 'Damaged', 'In Repair');


  create table "public"."categories" (
    "id" bigint generated always as identity not null,
    "name" text not null,
    "description" text
      );



  create table "public"."documents" (
    "id" bigint generated always as identity not null,
    "name" text not null,
    "url" text,
    "required" boolean default false
      );



  create table "public"."item_attachments" (
    "id" bigint generated always as identity not null,
    "item_id" bigint not null,
    "url" text not null,
    "name" text
      );



  create table "public"."item_images" (
    "id" bigint generated always as identity not null,
    "item_id" bigint not null,
    "url" text not null
      );



  create table "public"."item_locations" (
    "id" bigint generated always as identity not null,
    "name" text not null
      );



  create table "public"."items" (
    "id" bigint generated always as identity not null,
    "thing_id" bigint not null,
    "brand" text,
    "estimated_value" numeric(10,2),
    "hidden" boolean default false,
    "location_id" bigint,
    "notes" text,
    "number" bigint generated by default as identity not null,
    "status" public.status
      );



  create table "public"."loans" (
    "id" bigint generated always as identity not null,
    "checkout_date" timestamp with time zone not null default now(),
    "due_date" date not null,
    "notes" text,
    "member_id" bigint,
    "reminders_sent" bigint not null default '0'::bigint
      );



  create table "public"."loans_items" (
    "id" bigint generated by default as identity not null,
    "loan_id" bigint,
    "item_id" bigint,
    "returned" boolean not null default false,
    "thing_id" bigint
      );



  create table "public"."members" (
    "id" bigint generated always as identity not null,
    "name" text not null,
    "email" text not null,
    "join_date" date not null,
    "phone" text,
    "keyholder" boolean default false,
    "user_id" uuid
      );



  create table "public"."members_payments" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "member_id" bigint
      );



  create table "public"."signed_documents" (
    "id" bigint generated always as identity not null,
    "document_id" bigint not null,
    "member_id" bigint not null,
    "signed_at" timestamp with time zone default now()
      );



  create table "public"."thing_categories" (
    "thing_id" bigint not null,
    "category_id" bigint not null
      );



  create table "public"."thing_images" (
    "id" bigint generated always as identity not null,
    "thing_id" bigint not null,
    "url" text not null
      );



  create table "public"."things" (
    "id" bigint generated always as identity not null,
    "name" text not null,
    "description" text,
    "spanish_name" text,
    "hidden" boolean default false,
    "eye_protection" boolean not null default false
      );



  create table "public"."things_associations" (
    "id" bigint generated by default as identity not null,
    "thing_id" bigint not null,
    "associated_thing_id" bigint not null
      );


CREATE UNIQUE INDEX categories_name_key ON public.categories USING btree (name);

CREATE UNIQUE INDEX categories_pkey ON public.categories USING btree (id);

CREATE UNIQUE INDEX documents_pkey ON public.documents USING btree (id);

CREATE UNIQUE INDEX item_attachments_pkey ON public.item_attachments USING btree (id);

CREATE UNIQUE INDEX item_images_pkey ON public.item_images USING btree (id);

CREATE UNIQUE INDEX item_locations_pkey ON public.item_locations USING btree (id);

CREATE UNIQUE INDEX items_number_key ON public.items USING btree (number);

CREATE UNIQUE INDEX items_pkey ON public.items USING btree (id);

CREATE UNIQUE INDEX loans_items_pkey ON public.loans_items USING btree (id);

CREATE UNIQUE INDEX loans_pkey ON public.loans USING btree (id);

CREATE UNIQUE INDEX members_email_key ON public.members USING btree (email);

CREATE UNIQUE INDEX members_payments_pkey ON public.members_payments USING btree (id);

CREATE UNIQUE INDEX members_pkey ON public.members USING btree (id);

CREATE UNIQUE INDEX signed_documents_pkey ON public.signed_documents USING btree (id);

CREATE UNIQUE INDEX thing_categories_pkey ON public.thing_categories USING btree (thing_id, category_id);

CREATE UNIQUE INDEX thing_images_pkey ON public.thing_images USING btree (id);

CREATE UNIQUE INDEX things_associations_pkey ON public.things_associations USING btree (id);

CREATE UNIQUE INDEX things_pkey ON public.things USING btree (id);

alter table "public"."categories" add constraint "categories_pkey" PRIMARY KEY using index "categories_pkey";

alter table "public"."documents" add constraint "documents_pkey" PRIMARY KEY using index "documents_pkey";

alter table "public"."item_attachments" add constraint "item_attachments_pkey" PRIMARY KEY using index "item_attachments_pkey";

alter table "public"."item_images" add constraint "item_images_pkey" PRIMARY KEY using index "item_images_pkey";

alter table "public"."item_locations" add constraint "item_locations_pkey" PRIMARY KEY using index "item_locations_pkey";

alter table "public"."items" add constraint "items_pkey" PRIMARY KEY using index "items_pkey";

alter table "public"."loans" add constraint "loans_pkey" PRIMARY KEY using index "loans_pkey";

alter table "public"."loans_items" add constraint "loans_items_pkey" PRIMARY KEY using index "loans_items_pkey";

alter table "public"."members" add constraint "members_pkey" PRIMARY KEY using index "members_pkey";

alter table "public"."members_payments" add constraint "members_payments_pkey" PRIMARY KEY using index "members_payments_pkey";

alter table "public"."signed_documents" add constraint "signed_documents_pkey" PRIMARY KEY using index "signed_documents_pkey";

alter table "public"."thing_categories" add constraint "thing_categories_pkey" PRIMARY KEY using index "thing_categories_pkey";

alter table "public"."thing_images" add constraint "thing_images_pkey" PRIMARY KEY using index "thing_images_pkey";

alter table "public"."things" add constraint "things_pkey" PRIMARY KEY using index "things_pkey";

alter table "public"."things_associations" add constraint "things_associations_pkey" PRIMARY KEY using index "things_associations_pkey";

alter table "public"."categories" add constraint "categories_name_key" UNIQUE using index "categories_name_key";

alter table "public"."item_attachments" add constraint "item_attachments_item_id_fkey" FOREIGN KEY (item_id) REFERENCES public.items(id) ON DELETE CASCADE not valid;

alter table "public"."item_attachments" validate constraint "item_attachments_item_id_fkey";

alter table "public"."item_images" add constraint "item_images_item_id_fkey" FOREIGN KEY (item_id) REFERENCES public.items(id) ON DELETE CASCADE not valid;

alter table "public"."item_images" validate constraint "item_images_item_id_fkey";

alter table "public"."items" add constraint "items_location_id_fkey" FOREIGN KEY (location_id) REFERENCES public.item_locations(id) ON DELETE SET NULL not valid;

alter table "public"."items" validate constraint "items_location_id_fkey";

alter table "public"."items" add constraint "items_number_key" UNIQUE using index "items_number_key";

alter table "public"."items" add constraint "items_thing_id_fkey" FOREIGN KEY (thing_id) REFERENCES public.things(id) ON DELETE CASCADE not valid;

alter table "public"."items" validate constraint "items_thing_id_fkey";

alter table "public"."loans" add constraint "loans_member_id_fkey" FOREIGN KEY (member_id) REFERENCES public.members(id) ON UPDATE CASCADE not valid;

alter table "public"."loans" validate constraint "loans_member_id_fkey";

alter table "public"."loans_items" add constraint "loans_items_item_id_fkey" FOREIGN KEY (item_id) REFERENCES public.items(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."loans_items" validate constraint "loans_items_item_id_fkey";

alter table "public"."loans_items" add constraint "loans_items_loan_id_fkey" FOREIGN KEY (loan_id) REFERENCES public.loans(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."loans_items" validate constraint "loans_items_loan_id_fkey";

alter table "public"."loans_items" add constraint "loans_items_thing_id_fkey" FOREIGN KEY (thing_id) REFERENCES public.things(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."loans_items" validate constraint "loans_items_thing_id_fkey";

alter table "public"."members" add constraint "members_email_key" UNIQUE using index "members_email_key";

alter table "public"."members" add constraint "members_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."members" validate constraint "members_user_id_fkey";

alter table "public"."members_payments" add constraint "members_payments_member_id_fkey" FOREIGN KEY (member_id) REFERENCES public.members(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."members_payments" validate constraint "members_payments_member_id_fkey";

alter table "public"."signed_documents" add constraint "signed_documents_document_id_fkey" FOREIGN KEY (document_id) REFERENCES public.documents(id) ON DELETE CASCADE not valid;

alter table "public"."signed_documents" validate constraint "signed_documents_document_id_fkey";

alter table "public"."signed_documents" add constraint "signed_documents_member_id_fkey" FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE not valid;

alter table "public"."signed_documents" validate constraint "signed_documents_member_id_fkey";

alter table "public"."thing_categories" add constraint "thing_categories_category_id_fkey" FOREIGN KEY (category_id) REFERENCES public.categories(id) ON DELETE CASCADE not valid;

alter table "public"."thing_categories" validate constraint "thing_categories_category_id_fkey";

alter table "public"."thing_categories" add constraint "thing_categories_thing_id_fkey" FOREIGN KEY (thing_id) REFERENCES public.things(id) ON DELETE CASCADE not valid;

alter table "public"."thing_categories" validate constraint "thing_categories_thing_id_fkey";

alter table "public"."thing_images" add constraint "thing_images_thing_id_fkey" FOREIGN KEY (thing_id) REFERENCES public.things(id) ON DELETE CASCADE not valid;

alter table "public"."thing_images" validate constraint "thing_images_thing_id_fkey";

alter table "public"."things_associations" add constraint "things_associations_associated_thing_id_fkey" FOREIGN KEY (associated_thing_id) REFERENCES public.things(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."things_associations" validate constraint "things_associations_associated_thing_id_fkey";

alter table "public"."things_associations" add constraint "things_associations_thing_id_fkey" FOREIGN KEY (thing_id) REFERENCES public.things(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."things_associations" validate constraint "things_associations_thing_id_fkey";

grant delete on table "public"."categories" to "anon";

grant insert on table "public"."categories" to "anon";

grant references on table "public"."categories" to "anon";

grant select on table "public"."categories" to "anon";

grant trigger on table "public"."categories" to "anon";

grant truncate on table "public"."categories" to "anon";

grant update on table "public"."categories" to "anon";

grant delete on table "public"."categories" to "authenticated";

grant insert on table "public"."categories" to "authenticated";

grant references on table "public"."categories" to "authenticated";

grant select on table "public"."categories" to "authenticated";

grant trigger on table "public"."categories" to "authenticated";

grant truncate on table "public"."categories" to "authenticated";

grant update on table "public"."categories" to "authenticated";

grant delete on table "public"."categories" to "service_role";

grant insert on table "public"."categories" to "service_role";

grant references on table "public"."categories" to "service_role";

grant select on table "public"."categories" to "service_role";

grant trigger on table "public"."categories" to "service_role";

grant truncate on table "public"."categories" to "service_role";

grant update on table "public"."categories" to "service_role";

grant delete on table "public"."documents" to "anon";

grant insert on table "public"."documents" to "anon";

grant references on table "public"."documents" to "anon";

grant select on table "public"."documents" to "anon";

grant trigger on table "public"."documents" to "anon";

grant truncate on table "public"."documents" to "anon";

grant update on table "public"."documents" to "anon";

grant delete on table "public"."documents" to "authenticated";

grant insert on table "public"."documents" to "authenticated";

grant references on table "public"."documents" to "authenticated";

grant select on table "public"."documents" to "authenticated";

grant trigger on table "public"."documents" to "authenticated";

grant truncate on table "public"."documents" to "authenticated";

grant update on table "public"."documents" to "authenticated";

grant delete on table "public"."documents" to "service_role";

grant insert on table "public"."documents" to "service_role";

grant references on table "public"."documents" to "service_role";

grant select on table "public"."documents" to "service_role";

grant trigger on table "public"."documents" to "service_role";

grant truncate on table "public"."documents" to "service_role";

grant update on table "public"."documents" to "service_role";

grant delete on table "public"."item_attachments" to "anon";

grant insert on table "public"."item_attachments" to "anon";

grant references on table "public"."item_attachments" to "anon";

grant select on table "public"."item_attachments" to "anon";

grant trigger on table "public"."item_attachments" to "anon";

grant truncate on table "public"."item_attachments" to "anon";

grant update on table "public"."item_attachments" to "anon";

grant delete on table "public"."item_attachments" to "authenticated";

grant insert on table "public"."item_attachments" to "authenticated";

grant references on table "public"."item_attachments" to "authenticated";

grant select on table "public"."item_attachments" to "authenticated";

grant trigger on table "public"."item_attachments" to "authenticated";

grant truncate on table "public"."item_attachments" to "authenticated";

grant update on table "public"."item_attachments" to "authenticated";

grant delete on table "public"."item_attachments" to "service_role";

grant insert on table "public"."item_attachments" to "service_role";

grant references on table "public"."item_attachments" to "service_role";

grant select on table "public"."item_attachments" to "service_role";

grant trigger on table "public"."item_attachments" to "service_role";

grant truncate on table "public"."item_attachments" to "service_role";

grant update on table "public"."item_attachments" to "service_role";

grant delete on table "public"."item_images" to "anon";

grant insert on table "public"."item_images" to "anon";

grant references on table "public"."item_images" to "anon";

grant select on table "public"."item_images" to "anon";

grant trigger on table "public"."item_images" to "anon";

grant truncate on table "public"."item_images" to "anon";

grant update on table "public"."item_images" to "anon";

grant delete on table "public"."item_images" to "authenticated";

grant insert on table "public"."item_images" to "authenticated";

grant references on table "public"."item_images" to "authenticated";

grant select on table "public"."item_images" to "authenticated";

grant trigger on table "public"."item_images" to "authenticated";

grant truncate on table "public"."item_images" to "authenticated";

grant update on table "public"."item_images" to "authenticated";

grant delete on table "public"."item_images" to "service_role";

grant insert on table "public"."item_images" to "service_role";

grant references on table "public"."item_images" to "service_role";

grant select on table "public"."item_images" to "service_role";

grant trigger on table "public"."item_images" to "service_role";

grant truncate on table "public"."item_images" to "service_role";

grant update on table "public"."item_images" to "service_role";

grant delete on table "public"."item_locations" to "anon";

grant insert on table "public"."item_locations" to "anon";

grant references on table "public"."item_locations" to "anon";

grant select on table "public"."item_locations" to "anon";

grant trigger on table "public"."item_locations" to "anon";

grant truncate on table "public"."item_locations" to "anon";

grant update on table "public"."item_locations" to "anon";

grant delete on table "public"."item_locations" to "authenticated";

grant insert on table "public"."item_locations" to "authenticated";

grant references on table "public"."item_locations" to "authenticated";

grant select on table "public"."item_locations" to "authenticated";

grant trigger on table "public"."item_locations" to "authenticated";

grant truncate on table "public"."item_locations" to "authenticated";

grant update on table "public"."item_locations" to "authenticated";

grant delete on table "public"."item_locations" to "service_role";

grant insert on table "public"."item_locations" to "service_role";

grant references on table "public"."item_locations" to "service_role";

grant select on table "public"."item_locations" to "service_role";

grant trigger on table "public"."item_locations" to "service_role";

grant truncate on table "public"."item_locations" to "service_role";

grant update on table "public"."item_locations" to "service_role";

grant delete on table "public"."items" to "anon";

grant insert on table "public"."items" to "anon";

grant references on table "public"."items" to "anon";

grant select on table "public"."items" to "anon";

grant trigger on table "public"."items" to "anon";

grant truncate on table "public"."items" to "anon";

grant update on table "public"."items" to "anon";

grant delete on table "public"."items" to "authenticated";

grant insert on table "public"."items" to "authenticated";

grant references on table "public"."items" to "authenticated";

grant select on table "public"."items" to "authenticated";

grant trigger on table "public"."items" to "authenticated";

grant truncate on table "public"."items" to "authenticated";

grant update on table "public"."items" to "authenticated";

grant delete on table "public"."items" to "service_role";

grant insert on table "public"."items" to "service_role";

grant references on table "public"."items" to "service_role";

grant select on table "public"."items" to "service_role";

grant trigger on table "public"."items" to "service_role";

grant truncate on table "public"."items" to "service_role";

grant update on table "public"."items" to "service_role";

grant delete on table "public"."loans" to "anon";

grant insert on table "public"."loans" to "anon";

grant references on table "public"."loans" to "anon";

grant select on table "public"."loans" to "anon";

grant trigger on table "public"."loans" to "anon";

grant truncate on table "public"."loans" to "anon";

grant update on table "public"."loans" to "anon";

grant delete on table "public"."loans" to "authenticated";

grant insert on table "public"."loans" to "authenticated";

grant references on table "public"."loans" to "authenticated";

grant select on table "public"."loans" to "authenticated";

grant trigger on table "public"."loans" to "authenticated";

grant truncate on table "public"."loans" to "authenticated";

grant update on table "public"."loans" to "authenticated";

grant delete on table "public"."loans" to "service_role";

grant insert on table "public"."loans" to "service_role";

grant references on table "public"."loans" to "service_role";

grant select on table "public"."loans" to "service_role";

grant trigger on table "public"."loans" to "service_role";

grant truncate on table "public"."loans" to "service_role";

grant update on table "public"."loans" to "service_role";

grant delete on table "public"."loans_items" to "anon";

grant insert on table "public"."loans_items" to "anon";

grant references on table "public"."loans_items" to "anon";

grant select on table "public"."loans_items" to "anon";

grant trigger on table "public"."loans_items" to "anon";

grant truncate on table "public"."loans_items" to "anon";

grant update on table "public"."loans_items" to "anon";

grant delete on table "public"."loans_items" to "authenticated";

grant insert on table "public"."loans_items" to "authenticated";

grant references on table "public"."loans_items" to "authenticated";

grant select on table "public"."loans_items" to "authenticated";

grant trigger on table "public"."loans_items" to "authenticated";

grant truncate on table "public"."loans_items" to "authenticated";

grant update on table "public"."loans_items" to "authenticated";

grant delete on table "public"."loans_items" to "service_role";

grant insert on table "public"."loans_items" to "service_role";

grant references on table "public"."loans_items" to "service_role";

grant select on table "public"."loans_items" to "service_role";

grant trigger on table "public"."loans_items" to "service_role";

grant truncate on table "public"."loans_items" to "service_role";

grant update on table "public"."loans_items" to "service_role";

grant delete on table "public"."members" to "anon";

grant insert on table "public"."members" to "anon";

grant references on table "public"."members" to "anon";

grant select on table "public"."members" to "anon";

grant trigger on table "public"."members" to "anon";

grant truncate on table "public"."members" to "anon";

grant update on table "public"."members" to "anon";

grant delete on table "public"."members" to "authenticated";

grant insert on table "public"."members" to "authenticated";

grant references on table "public"."members" to "authenticated";

grant select on table "public"."members" to "authenticated";

grant trigger on table "public"."members" to "authenticated";

grant truncate on table "public"."members" to "authenticated";

grant update on table "public"."members" to "authenticated";

grant delete on table "public"."members" to "service_role";

grant insert on table "public"."members" to "service_role";

grant references on table "public"."members" to "service_role";

grant select on table "public"."members" to "service_role";

grant trigger on table "public"."members" to "service_role";

grant truncate on table "public"."members" to "service_role";

grant update on table "public"."members" to "service_role";

grant delete on table "public"."members_payments" to "anon";

grant insert on table "public"."members_payments" to "anon";

grant references on table "public"."members_payments" to "anon";

grant select on table "public"."members_payments" to "anon";

grant trigger on table "public"."members_payments" to "anon";

grant truncate on table "public"."members_payments" to "anon";

grant update on table "public"."members_payments" to "anon";

grant delete on table "public"."members_payments" to "authenticated";

grant insert on table "public"."members_payments" to "authenticated";

grant references on table "public"."members_payments" to "authenticated";

grant select on table "public"."members_payments" to "authenticated";

grant trigger on table "public"."members_payments" to "authenticated";

grant truncate on table "public"."members_payments" to "authenticated";

grant update on table "public"."members_payments" to "authenticated";

grant delete on table "public"."members_payments" to "service_role";

grant insert on table "public"."members_payments" to "service_role";

grant references on table "public"."members_payments" to "service_role";

grant select on table "public"."members_payments" to "service_role";

grant trigger on table "public"."members_payments" to "service_role";

grant truncate on table "public"."members_payments" to "service_role";

grant update on table "public"."members_payments" to "service_role";

grant delete on table "public"."signed_documents" to "anon";

grant insert on table "public"."signed_documents" to "anon";

grant references on table "public"."signed_documents" to "anon";

grant select on table "public"."signed_documents" to "anon";

grant trigger on table "public"."signed_documents" to "anon";

grant truncate on table "public"."signed_documents" to "anon";

grant update on table "public"."signed_documents" to "anon";

grant delete on table "public"."signed_documents" to "authenticated";

grant insert on table "public"."signed_documents" to "authenticated";

grant references on table "public"."signed_documents" to "authenticated";

grant select on table "public"."signed_documents" to "authenticated";

grant trigger on table "public"."signed_documents" to "authenticated";

grant truncate on table "public"."signed_documents" to "authenticated";

grant update on table "public"."signed_documents" to "authenticated";

grant delete on table "public"."signed_documents" to "service_role";

grant insert on table "public"."signed_documents" to "service_role";

grant references on table "public"."signed_documents" to "service_role";

grant select on table "public"."signed_documents" to "service_role";

grant trigger on table "public"."signed_documents" to "service_role";

grant truncate on table "public"."signed_documents" to "service_role";

grant update on table "public"."signed_documents" to "service_role";

grant delete on table "public"."thing_categories" to "anon";

grant insert on table "public"."thing_categories" to "anon";

grant references on table "public"."thing_categories" to "anon";

grant select on table "public"."thing_categories" to "anon";

grant trigger on table "public"."thing_categories" to "anon";

grant truncate on table "public"."thing_categories" to "anon";

grant update on table "public"."thing_categories" to "anon";

grant delete on table "public"."thing_categories" to "authenticated";

grant insert on table "public"."thing_categories" to "authenticated";

grant references on table "public"."thing_categories" to "authenticated";

grant select on table "public"."thing_categories" to "authenticated";

grant trigger on table "public"."thing_categories" to "authenticated";

grant truncate on table "public"."thing_categories" to "authenticated";

grant update on table "public"."thing_categories" to "authenticated";

grant delete on table "public"."thing_categories" to "service_role";

grant insert on table "public"."thing_categories" to "service_role";

grant references on table "public"."thing_categories" to "service_role";

grant select on table "public"."thing_categories" to "service_role";

grant trigger on table "public"."thing_categories" to "service_role";

grant truncate on table "public"."thing_categories" to "service_role";

grant update on table "public"."thing_categories" to "service_role";

grant delete on table "public"."thing_images" to "anon";

grant insert on table "public"."thing_images" to "anon";

grant references on table "public"."thing_images" to "anon";

grant select on table "public"."thing_images" to "anon";

grant trigger on table "public"."thing_images" to "anon";

grant truncate on table "public"."thing_images" to "anon";

grant update on table "public"."thing_images" to "anon";

grant delete on table "public"."thing_images" to "authenticated";

grant insert on table "public"."thing_images" to "authenticated";

grant references on table "public"."thing_images" to "authenticated";

grant select on table "public"."thing_images" to "authenticated";

grant trigger on table "public"."thing_images" to "authenticated";

grant truncate on table "public"."thing_images" to "authenticated";

grant update on table "public"."thing_images" to "authenticated";

grant delete on table "public"."thing_images" to "service_role";

grant insert on table "public"."thing_images" to "service_role";

grant references on table "public"."thing_images" to "service_role";

grant select on table "public"."thing_images" to "service_role";

grant trigger on table "public"."thing_images" to "service_role";

grant truncate on table "public"."thing_images" to "service_role";

grant update on table "public"."thing_images" to "service_role";

grant delete on table "public"."things" to "anon";

grant insert on table "public"."things" to "anon";

grant references on table "public"."things" to "anon";

grant select on table "public"."things" to "anon";

grant trigger on table "public"."things" to "anon";

grant truncate on table "public"."things" to "anon";

grant update on table "public"."things" to "anon";

grant delete on table "public"."things" to "authenticated";

grant insert on table "public"."things" to "authenticated";

grant references on table "public"."things" to "authenticated";

grant select on table "public"."things" to "authenticated";

grant trigger on table "public"."things" to "authenticated";

grant truncate on table "public"."things" to "authenticated";

grant update on table "public"."things" to "authenticated";

grant delete on table "public"."things" to "service_role";

grant insert on table "public"."things" to "service_role";

grant references on table "public"."things" to "service_role";

grant select on table "public"."things" to "service_role";

grant trigger on table "public"."things" to "service_role";

grant truncate on table "public"."things" to "service_role";

grant update on table "public"."things" to "service_role";

grant delete on table "public"."things_associations" to "anon";

grant insert on table "public"."things_associations" to "anon";

grant references on table "public"."things_associations" to "anon";

grant select on table "public"."things_associations" to "anon";

grant trigger on table "public"."things_associations" to "anon";

grant truncate on table "public"."things_associations" to "anon";

grant update on table "public"."things_associations" to "anon";

grant delete on table "public"."things_associations" to "authenticated";

grant insert on table "public"."things_associations" to "authenticated";

grant references on table "public"."things_associations" to "authenticated";

grant select on table "public"."things_associations" to "authenticated";

grant trigger on table "public"."things_associations" to "authenticated";

grant truncate on table "public"."things_associations" to "authenticated";

grant update on table "public"."things_associations" to "authenticated";

grant delete on table "public"."things_associations" to "service_role";

grant insert on table "public"."things_associations" to "service_role";

grant references on table "public"."things_associations" to "service_role";

grant select on table "public"."things_associations" to "service_role";

grant trigger on table "public"."things_associations" to "service_role";

grant truncate on table "public"."things_associations" to "service_role";

grant update on table "public"."things_associations" to "service_role";


